$(document).ready(function(){
    $('#owl-logo').owlCarousel({
      loop:true,
  margin:10,
  nav:false,
  responsive:{
      0:{
          items:3
      },
      600:{
          items:3
      },
      1000:{
          items:5,
          dots: true
      }
  }
  })
})
  $(document).ready(function(){
$(".owl-carousel").owlCarousel({
  loop:true,
  margin:10,
  nav:false,
  responsiveClass:true,
  responsive:{
      0:{
          items:1
      },
      600:{
          items:1
      },
      1000:{
          items:3,
      }
  }
  })
  })